### ISSUE TITLE
No Gazebo access on Windows

### ISSUE THREAD

**Issue by arthurrichards77** [StarlingUAS/FenswoodScenario#4]
Can't access localhost:8080 on Windows - just get connection refused, and Docker Desktop shows no ports available.  Output messages show Gazebo listening on 8080 though.  Suspect problem is that host networking is not permitted on Windows.

Tried with a modified version of the compose file as below.  That enabled me to get a Gazebo window up in my browser *but* also gave lots of error messages from mavros, indicating that it could no longer find the FCU URL, presumably due to the network change,

`version: '3'

services:
  simhost:
    image: uobflightlabstarling/starling-sim-iris-ap:latest
    volumes:
      - ./fenswood:/ros.env.d/fenswood
    command: ["ros2", "launch", "/ros.env.d/fenswood/iris.launch.xml"]
    ports:
      - 8080:8080

  sitl:
    image: uobflightlabstarling/starling-sim-ardupilot-copter:latest
    environment:
      - AP_USE_GAZEBO=true
      - AP_HOME=51.4233628,-2.671671,100.0,0
  
  mavros:
    image: uobflightlabstarling/starling-mavros:latest
    command: ros2 launch launch/mavros_bridge.launch.xml
    environment:
      - "MAVROS_TGT_FIRMWARE=apm"
      - "MAVROS_TGT_SYSTEM=1"
      - "MAVROS_FCU_URL=tcp://127.0.0.1:5760"
      - "MAVROS_CONFIG_PATH=/mavros_config_ap.yaml"
      - "MAVROS_PLUGINLISTS_PATH=/mavros_pluginlists_ap.yaml"`

**Comment by arthurrichards77** [comment]
OK - we'll talk on Monday about this, but I'm confused for two reasons:
1. the error message I was seeing was related, I think, to the MAVROS container talking to the SITL instance.  Maybe I missed other errors related to the SITL<->Gazebo link, but the main recurring one was definitely MAVROS<->SITL.
2. I had no such problems on the main Starling single-drone sim docker-compose app.  Has something been taken out?  Or is this a result of the switch to Ardupilot?  I feel like all the capability to look up IP addresses of other containers in the network must already exist.  Is it just a matter of re-applying it here or am I missing a more fundamental challenge?

**Comment by rob-clarke** [comment]
On 1, yes likely the SITL <-> Gazebo problems were hidden by the MAVROS ones. `MAVROS_FCU_URL` will need to be adjusted to point to the SITL container. This was not a problem with network host as everything was using loopback IP.

The same thing applies to the SITL -> Gazebo link but some more mechanics need to be in place to make the adjustment. Regarding 2, yes this is ArduPilot specific, we hadn't yet got a method of exposing how to set the IPs used by the SITL to talk to the sim. The new branch adds that.

The SITL, and ArduPilot's Gazebo plug-in, won't be able to cope with plain hostnames so we'll need to add the host -> IP lookups. We've already done something similar for the PX4 images so this shouldn't be a problem.
